# -*- coding: utf-8 -*-
"""forbidden_question_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXjYMg5-gpXLEA0RTwRpErTl6JH3xIvF
"""

pip install transformers torch scikit-learn

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import AdamW
from tqdm import tqdm

# Load the dataset
file_path = "/kaggle/input/newly-dataset/dataset_questions.csv"  # Replace with your file path
data = pd.read_csv(file_path)

# Split dataset
train_data, test_data = train_test_split(
    data, test_size=0.2, random_state=42, stratify=data['label']
)

# Tokenization
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

def tokenize_data(dataframe, tokenizer, max_length=128):
    return tokenizer(
        list(dataframe['question']),
        max_length=max_length,
        padding='max_length',
        truncation=True,
        return_tensors='pt'
    )

train_encodings = tokenize_data(train_data, tokenizer)
test_encodings = tokenize_data(test_data, tokenizer)

train_labels = torch.tensor(train_data['label'].values)
test_labels = torch.tensor(test_data['label'].values)

# Dataset class
class QuestionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            key: val[idx] for key, val in self.encodings.items()
        }, self.labels[idx]

train_dataset = QuestionDataset(train_encodings, train_labels)
test_dataset = QuestionDataset(test_encodings, test_labels)

# DataLoader
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

# Model
model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=len(data['label'].unique())
)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)

# Optimizer
optimizer = AdamW(model.parameters(), lr=5e-5)

# Training and Evaluation
for epoch in range(3):
    print(f"Epoch {epoch + 1}/3")

    # Training phase
    model.train()
    total_loss = 0
    for batch in tqdm(train_loader, desc=f"Training Epoch {epoch + 1}", leave=False):
        inputs, labels = batch
        inputs = {key: val.to(device) for key, val in inputs.items()}
        labels = labels.to(device)
        optimizer.zero_grad()
        outputs = model(**inputs, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Training completed for Epoch {epoch + 1}. Average Loss: {total_loss / len(train_loader):.4f}")

    # Evaluation phase
    model.eval()
    predictions, true_labels = [], []
    with torch.no_grad():
        for batch in tqdm(test_loader, desc=f"Evaluating Epoch {epoch + 1}", leave=False):
            inputs, labels = batch
            inputs = {key: val.to(device) for key, val in inputs.items()}
            labels = labels.to(device)
            outputs = model(**inputs)
            logits = outputs.logits
            predictions.extend(torch.argmax(logits, axis=1).cpu().numpy())
            true_labels.extend(labels.cpu().numpy())

    print(f"Evaluation for Epoch {epoch + 1}:")
    print(classification_report(true_labels, predictions, digits=4))

import os

# Define the directory to save the model
output_dir = "/kaggle/working/saved_model"

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Save the model and tokenizer
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

print(f"Model and tokenizer saved to {output_dir}")

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Generate and plot the confusion matrix
def plot_confusion_matrix(true_labels, predictions, class_names, save_path=None):
    cm = confusion_matrix(true_labels, predictions)
    plt.figure(figsize=(10, 7))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.xlabel("Predicted Labels")
    plt.ylabel("True Labels")
    plt.title("Confusion Matrix")

    if save_path:
        plt.savefig(save_path, bbox_inches="tight")  # Save the figure
        print(f"Confusion matrix saved to {save_path}")

    plt.show()

# After evaluation phase
class_names = data['label'].unique()  # Replace this with actual class names if available
output_path = "confusion_matrix.png"  # Specify the desired file name and format
plot_confusion_matrix(true_labels, predictions, class_names, save_path=output_path)

pip install lime

from lime.lime_text import LimeTextExplainer
import numpy as np
import torch

# Optimized predict_proba function using CPU
def predict_proba(texts):
    # Move model to CPU
    device_cpu = torch.device("cpu")
    model.to(device_cpu)
    model.eval()

    probs = []
    for text in texts:
        # Tokenize input text
        encodings = tokenizer([text], padding='max_length', truncation=True, max_length=128, return_tensors='pt')
        encodings = {key: val.to(device_cpu) for key, val in encodings.items()}

        # Get prediction probabilities
        with torch.no_grad():
            logits = model(**encodings).logits
            prob = torch.softmax(logits, dim=1).cpu().numpy()
        probs.append(prob)

    # Return probabilities as a NumPy array
    return np.vstack(probs)

# Initialize LIME Text Explainer
explainer = LimeTextExplainer(class_names=data['label'].unique().tolist())

# Clear GPU memory cache
torch.cuda.empty_cache()

# Select a sample to explain
sample_text = test_data.iloc[0]['question']
sample_label = test_data.iloc[0]['label']
print(f"Sample Text: {sample_text}")
print(f"True Label: {sample_label}")

# Explain the prediction
exp = explainer.explain_instance(
    sample_text,
    predict_proba,
    num_features=10,
    top_labels=1
)

# Visualize the explanation in notebook
exp.show_in_notebook(text=True)

# Save explanation to an HTML file
exp.save_to_file("lime_explanation.html")

# Move model back to GPU for further computations
model.to(device)