# -*- coding: utf-8 -*-
"""JailBreakBERT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRmHHv2ujMY9SdG2o85P0n-HYIuDrio4

**Exploratory Data Analysis**
"""

import pandas as pd

# Load the dataset
file_path = '/content/merged(in).csv'
data = pd.read_csv(file_path)

# Display basic information about the dataset
data_info = {
    "head": data.head(),
    "shape": data.shape,
    "columns": data.columns.tolist(),
    "class_distribution": data['jailbreak'].value_counts()
}

data_info

import matplotlib.pyplot as plt

# Drop unnecessary columns
data_cleaned = data[['prompt', 'jailbreak']]

# Filter out invalid rows where 'jailbreak' is not TRUE or FALSE
valid_classes = ['TRUE', 'FALSE']
data_cleaned = data_cleaned[data_cleaned['jailbreak'].isin(valid_classes)]

# Updated class distribution
class_distribution = data_cleaned['jailbreak'].value_counts()

# Plotting the class distribution
plt.figure(figsize=(6, 4))
class_distribution.plot(kind='bar', color=['skyblue', 'salmon'], rot=0)
plt.title("Class Distribution of Jailbreaking Prompts")
plt.xlabel("Jailbreak Label")
plt.ylabel("Count")
plt.xticks(ticks=[0, 1], labels=['FALSE', 'TRUE'], rotation=0)
plt.show()

# Output cleaned dataset info
data_cleaned_info = {
    "cleaned_shape": data_cleaned.shape,
    "cleaned_class_distribution": class_distribution
}
data_cleaned_info

from wordcloud import WordCloud

# Combine all prompts into a single text for the word cloud
text_data = " ".join(data_cleaned['prompt'])

# Generate a word cloud
wordcloud = WordCloud(width=800, height=400, background_color="white").generate(text_data)

# Display the word cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.title("Word Cloud of Jailbreaking Prompts", fontsize=16)
plt.show()

"""**Synthetic Prompts Generation**"""

# Filter dataset for minority class
minority_prompts = data_cleaned[data_cleaned['jailbreak'] == 'TRUE']['prompt']

# Save these prompts to a file (e.g., a text file) for training
minority_prompts.to_csv('minority_prompts.txt', index=False, header=False)

!pip install transformers datasets torch

from transformers import GPT2Tokenizer, GPT2LMHeadModel, TextDataset, DataCollatorForLanguageModeling, Trainer, TrainingArguments

# Load the tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Prepare the dataset
def load_dataset(file_path, tokenizer, block_size=128):
    return TextDataset(
        tokenizer=tokenizer,
        file_path=file_path,
        block_size=block_size,
    )

dataset = load_dataset("minority_prompts.txt", tokenizer)

# Prepare data collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=False
)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    overwrite_output_dir=True,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    save_steps=500,
    save_total_limit=2,
    prediction_loss_only=True,
)

# Create Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset,
)

# Fine-tune the model
trainer.train()

# Save the fine-tuned model
model.save_pretrained("./fine_tuned_model")
tokenizer.save_pretrained("./fine_tuned_model")

from transformers import pipeline

# Load the fine-tuned model
generator = pipeline('text-generation', model='./fine_tuned_model', tokenizer='./fine_tuned_model')

# Generate new prompts
synthetic_prompts = generator("Write a jailbreak prompt:", max_length=50, num_return_sequences=10)

# Print synthetic prompts
for i, prompt in enumerate(synthetic_prompts):
    print(f"Synthetic Prompt {i+1}: {prompt['generated_text']}")

from transformers import pipeline
import torch
import gc

# Load the fine-tuned model
device = "cuda" if torch.cuda.is_available() else "cpu"
generator = pipeline('text-generation', model='./fine_tuned_model', tokenizer='./fine_tuned_model', device=0 if device == "cuda" else -1)

# Function to generate synthetic prompts in batches
def generate_synthetic_prompts(batch_size, num_batches, max_length=50):
    synthetic_prompts = []

    for batch_num in range(num_batches):
        print(f"Generating batch {batch_num + 1}/{num_batches}...")

        # Generate prompts for the current batch
        batch_prompts = generator(
            "Write a jailbreak prompt:",
            max_length=max_length,
            num_return_sequences=batch_size
        )

        # Extract generated text and store it
        synthetic_prompts.extend([prompt['generated_text'] for prompt in batch_prompts])

        # Clear memory and cache
        gc.collect()
        if device == "cuda":
            torch.cuda.empty_cache()

    return synthetic_prompts

# Define parameters
batch_size = 100  # Number of prompts per batch
num_batches = 140  # Total batches to reach 14,000 prompts

# Generate synthetic prompts
synthetic_prompts = generate_synthetic_prompts(batch_size, num_batches)

# Save the prompts to a file
with open('synthetic_prompts.txt', 'w') as f:
    for prompt in synthetic_prompts:
        f.write(prompt + '\n')

print("Synthetic prompt generation complete. Saved to 'synthetic_prompts.txt'.")

import pandas as pd

# Load the original dataset
file_path = "/content/merged(in).csv"  # Replace with the actual file path
data = pd.read_csv(file_path)

# Ensure the labels are binary
data['jailbreak'] = data['jailbreak'].apply(lambda x: 1 if x == 'TRUE' else 0)

# Load synthetic prompts from the saved file
synthetic_file = 'synthetic_prompts.txt'
with open(synthetic_file, 'r') as f:
    synthetic_prompts = f.readlines()

# Clean synthetic prompts
synthetic_prompts = [prompt.strip() for prompt in synthetic_prompts if prompt.strip()]

# Create a DataFrame for synthetic prompts
synthetic_df = pd.DataFrame({
    'prompt': synthetic_prompts,
    'jailbreak': 1  # Assign label 1 (TRUE) for all synthetic prompts
})

# Combine original dataset with synthetic prompts
augmented_data = pd.concat([data, synthetic_df], ignore_index=True)

# Shuffle the augmented dataset for better training
augmented_data = augmented_data.sample(frac=1).reset_index(drop=True)

# Save the augmented dataset to a new CSV file
augmented_file = "/content/augmented_dataset.csv"
augmented_data.to_csv(augmented_file, index=False)

print(f"Augmented dataset saved to {augmented_file}.")

# Load the augmented dataset to verify class distribution
augmented_file = '/content/augmented_dataset.csv'
augmented_data = pd.read_csv(augmented_file)

# Calculate class distribution
class_distribution = augmented_data['jailbreak'].value_counts()

class_distribution

import pandas as pd
import matplotlib.pyplot as plt

# Load the augmented dataset
augmented_file = '/content/augmented_dataset.csv'
augmented_data = pd.read_csv(augmented_file)

# Calculate class distribution
class_counts = augmented_data['jailbreak'].value_counts()

# Plot class distribution
plt.figure(figsize=(8, 5))
plt.bar(class_counts.index, class_counts.values, color=['blue', 'orange'])
plt.xticks(ticks=[0, 1], labels=['False', 'True'])
plt.title('Class Distribution in Augmented Dataset', fontsize=14)
plt.xlabel('Class', fontsize=12)
plt.ylabel('Number of Samples', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**JailBreakBERT**"""

!pip install transformers datasets torch scikit-learn

from sklearn.utils import resample

# Separate the majority and minority classes
majority_class = augmented_data[augmented_data['jailbreak'] == 1]
minority_class = augmented_data[augmented_data['jailbreak'] == 0]

# Downsample the majority class to 16,000 samples
majority_downsampled = resample(
    majority_class,
    replace=False,  # Sampling without replacement
    n_samples=16000,
    random_state=42
)

# Combine the minority class and downsampled majority class
balanced_data = pd.concat([majority_downsampled, minority_class])
balanced_data = balanced_data.sample(frac=1).reset_index(drop=True)  # Shuffle the dataset

from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X = balanced_data['prompt']
y = balanced_data['jailbreak']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from transformers import BertTokenizer

# Load BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize the data
def tokenize_data(texts, tokenizer, max_length=128):
    # Ensure all elements in 'texts' are strings
    texts = [str(text) for text in texts]  # Convert to strings using str()
    return tokenizer(
        texts,  # Pass the updated list of strings
        max_length=max_length,
        padding=True,
        truncation=True,
        return_tensors="pt"
    )

train_encodings = tokenize_data(X_train, tokenizer)
test_encodings = tokenize_data(X_test, tokenizer)

import torch

# Create PyTorch datasets
class PromptDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Convert labels to lists for dataset initialization
train_labels = y_train.tolist()
test_labels = y_test.tolist()

# Initialize datasets
train_dataset = PromptDataset(train_encodings, train_labels)
test_dataset = PromptDataset(test_encodings, test_labels)

from transformers import BertForSequenceClassification, Trainer, TrainingArguments

# Load pre-trained BERT model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=2)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=100,
    load_best_model_at_end=True
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(f"Evaluation Results: {eval_results}")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import torch

# Get the device the model is on
device = next(model.parameters()).device

# Predict on the test set
model.eval()
predictions = []
true_labels = []

with torch.no_grad():
    for batch in test_dataset:
        # Move input tensors to the same device as the model
        input_ids = batch['input_ids'].unsqueeze(0).to(device)
        attention_mask = batch['attention_mask'].unsqueeze(0).to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        predicted_class = torch.argmax(logits, dim=1).item()

        predictions.append(predicted_class)
        true_labels.append(batch['labels'].item())

# Calculate evaluation metrics
accuracy = accuracy_score(true_labels, predictions)
precision = precision_score(true_labels, predictions)
recall = recall_score(true_labels, predictions)
f1 = f1_score(true_labels, predictions)

# Print the metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

# Compute confusion matrix
cm = confusion_matrix(true_labels, predictions)

# Plot the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["False", "True"])
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix")
plt.show()

# Define a directory to save the model and tokenizer
output_dir = "/content/saved_bert_model"

# Save the model
model.save_pretrained(output_dir)

# Save the tokenizer
tokenizer.save_pretrained(output_dir)

print(f"Model and tokenizer saved to: {output_dir}")