# -*- coding: utf-8 -*-
"""XAI_JailBreakRoBERTa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d67yLx0DRL6HxzWoyO7_wtzEMmXhycdd

**Exploratory Data Analysis**
"""

import pandas as pd

# Load the dataset
file_path = '/content/augmented_dataset.csv'
data = pd.read_csv(file_path)

# Display basic information about the dataset
data_info = {
    "head": data.head(),
    "shape": data.shape,
    "columns": data.columns.tolist(),
    "class_distribution": data['jailbreak'].value_counts()
}

data_info

import matplotlib.pyplot as plt

# Drop unnecessary columns
data_cleaned = data[['prompt', 'jailbreak']]

valid_classes = [0, 1]
data_cleaned = data_cleaned[data_cleaned['jailbreak'].isin(valid_classes)]

# Updated class distribution
class_distribution = data_cleaned['jailbreak'].value_counts()

# Plotting the class distribution
plt.figure(figsize=(6, 4))
class_distribution.plot(kind='bar', color=['skyblue', 'salmon'], rot=0)
plt.title("Class Distribution of Jailbreaking Prompts")
plt.xlabel("Jailbreak Label")
plt.ylabel("Count")
plt.xticks(ticks=[0, 1], labels=['TRUE', 'FALSE'], rotation=0)
plt.show()

# Output cleaned dataset info
data_cleaned_info = {
    "cleaned_shape": data_cleaned.shape,
    "cleaned_class_distribution": class_distribution
}
data_cleaned_info

"""**JailBreakRoBERTa**"""

!pip install transformers datasets torch scikit-learn

from sklearn.utils import resample

# Separate the majority and minority classes
majority_class = data_cleaned[data_cleaned['jailbreak'] == 1]
minority_class = data_cleaned[data_cleaned['jailbreak'] == 0]

# Downsample the majority class to 16,000 samples
majority_downsampled = resample(
    majority_class,
    replace=False,  # Sampling without replacement
    n_samples=16000,
    random_state=42
)

# Combine the minority class and downsampled majority class
balanced_data = pd.concat([majority_downsampled, minority_class])
balanced_data = balanced_data.sample(frac=1).reset_index(drop=True)  # Shuffle the dataset

from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X = balanced_data['prompt']
y = balanced_data['jailbreak']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from transformers import RobertaTokenizer

# Load RoBERTa tokenizer
tokenizer = RobertaTokenizer.from_pretrained('roberta-base')

# Tokenize the data
def tokenize_data(texts, tokenizer, max_length=128):
    # Ensure all elements in 'texts' are strings
    texts = [str(text) for text in texts]  # Convert to strings using str()
    return tokenizer(
        texts,  # Pass the updated list of strings
        max_length=max_length,
        padding=True,
        truncation=True,
        return_tensors="pt"
    )

train_encodings = tokenize_data(X_train, tokenizer)
test_encodings = tokenize_data(X_test, tokenizer)

import torch

# Create PyTorch datasets
class PromptDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Convert labels to lists for dataset initialization
train_labels = y_train.tolist()
test_labels = y_test.tolist()

# Initialize datasets
train_dataset = PromptDataset(train_encodings, train_labels)
test_dataset = PromptDataset(test_encodings, test_labels)

from transformers import RobertaForSequenceClassification, Trainer, TrainingArguments

# Load pre-trained RoBERTa model
model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=2)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=100,
    load_best_model_at_end=True
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(f"Evaluation Results: {eval_results}")

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay
import torch

# Get the device the model is on
device = next(model.parameters()).device

# Predict on the test set
model.eval()
predictions = []
true_labels = []

with torch.no_grad():
    for batch in test_dataset:
        # Move input tensors to the same device as the model
        input_ids = batch['input_ids'].unsqueeze(0).to(device)
        attention_mask = batch['attention_mask'].unsqueeze(0).to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        predicted_class = torch.argmax(logits, dim=1).item()

        predictions.append(predicted_class)
        true_labels.append(batch['labels'].item())

# Calculate evaluation metrics
accuracy = accuracy_score(true_labels, predictions)
precision = precision_score(true_labels, predictions)
recall = recall_score(true_labels, predictions)
f1 = f1_score(true_labels, predictions)

# Print the metrics
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

# Compute confusion matrix
cm = confusion_matrix(true_labels, predictions)

# Plot the confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["False", "True"])
disp.plot(cmap="Blues", values_format="d")
plt.title("Confusion Matrix")
plt.show()

# Define a directory to save the model and tokenizer
output_dir = "/content/saved_bert_model"

# Save the model
model.save_pretrained(output_dir)

# Save the tokenizer
tokenizer.save_pretrained(output_dir)

print(f"Model and tokenizer saved to: {output_dir}")

"""**XAI using LIME**"""

!pip install lime

import torch
from transformers import RobertaTokenizer, RobertaForSequenceClassification
import numpy as np

# Load the model and tokenizer
model = RobertaForSequenceClassification.from_pretrained('/content/saved_bert_model')
tokenizer = RobertaTokenizer.from_pretrained('/content/saved_bert_model')

# Make sure the model is in evaluation mode
model.eval()

# Define the prediction function for LIME
def predict_proba(texts):
    # Tokenize the input texts
    encodings = tokenizer(texts, padding=True, truncation=True, max_length=128, return_tensors="pt")
    with torch.no_grad():
        # Forward pass through the model
        outputs = model(**encodings)
        logits = outputs.logits
        probs = torch.nn.functional.softmax(logits, dim=-1)

    # Convert probabilities to numpy array
    return probs.numpy()

from lime.lime_text import LimeTextExplainer

# Initialize the LimeTextExplainer
explainer = LimeTextExplainer(class_names=['Class 0', 'Class 1'])  # Adjust class names as per your task

# Select a sample from the test set (e.g., the first text in the test set)
sample_text = X_test[0]

# Explain the prediction for the sample
explanation = explainer.explain_instance(sample_text, predict_proba, num_features=10)

# Visualize the explanation
explanation.show_in_notebook(text=True)

from lime.lime_text import LimeTextExplainer

# Initialize the LimeTextExplainer
explainer = LimeTextExplainer(class_names=['Class 0', 'Class 1'])  # Adjust class names as per your task

# Define a function to explain predictions for multiple samples
def explain_multiple_samples(samples, model, tokenizer, num_features=10):
    explanations = []
    for i, sample_text in enumerate(samples[:2]):  # Get first 2 samples
        # Explain the prediction for each sample
        explanation = explainer.explain_instance(sample_text, model, num_features=num_features)
        explanations.append(explanation)
        print(f"Explanation for sample {i+1}:")
        explanation.show_in_notebook(text=True)

    return explanations

# Select the first 2 samples from the test set
first_2_samples = X_test[:2]

# Explain predictions for the first 2 samples
explanations = explain_multiple_samples(first_2_samples, predict_proba, tokenizer) # Pass tokenizer as argument